dependencies:
  - cachetools
  - ffmpeg
  - line_profiler
  - matplotlib
  - numpy
  - pandas
  - pip
  - protobuf
  - pyarrow
  - python
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow=2.8.1=cuda*
  - pip:
    - awscli
    - boto3
    - ftfy
    - fiftyone
    - git+https://github.com/divamgupta/stable-diffusion-tensorflow.git@2873079b49eda63f41267c69b825e03cbcb2c308
    - ipykernel
    - ipython
    - ipywidgets
    - kaggle
    - keras-tuner
    - regex
    - requests
    - s3fs
    - tensorflow-hub
    - tensorflow_addons
    - transformers
    - tqdm
