dependencies:
  - boto3
  - cachetools
  - cudnn
  - ffmpeg
  - ipython
  - ipykernel
  - ipywidgets
  - line_profiler
  - matplotlib
  - numpy
  - pandas
  - pip
  - protobuf
  - pyarrow
  - python
  - s3fs
  - scikit-learn
  - seaborn
  - statsmodels
  - pip:
    - awscli
    - ftfy
    - regex
    - git+https://github.com/divamgupta/stable-diffusion-tensorflow.git
    - keras-tuner
    - requests
    - tensorflow-gpu
    - tensorflow-hub
    - tensorflow_addons
    - tqdm