dependencies:
  - boto3=1.15.1
  - cachetools=4.1.1
  - ffmpeg
  - ipython>=7.10
  - ipykernel>=5
  - ipywidgets=7.5.1
  - jupyterlab=2.3.2
  - jupyterlab-git=0.21.1
  - line_profiler>=2
  - matplotlib>=3
  - mlflow=1.10.0
  - nbconvert=5.6.1
  - nodejs>=12
  - numpy>=1.15
  - pandas=1.1.0
  - pip
  - protobuf=3.11.2
  - pyarrow>=0.11
  - python=3.8.5
  - requests>=2
  - s3fs
  - scikit-learn>=0.21
  - seaborn>=0.9
  - statsmodels=0.11.1
  - tensorflow-gpu=2.2.0
  - tensorflow-estimator=2.2.0
  - tensorflow-hub=0.8.0
  - x264
  - pip:
      - awscli
      - git+https://github.com/keras-team/keras-tuner@1.0.2rc1
