dependencies:
  - boto3
  - cachetools
  - ffmpeg
  - ipython
  - ipykernel
  - ipywidgets
  - line_profiler
  - matplotlib
  - numpy
  - pandas
  - pip
  - protobuf
  - pyarrow
  - python
  - s3fs
  - scikit-learn
  - seaborn
  - statsmodels
  - tensorflow-gpu
  - tensorflow-estimator
  - tensorflow-hub
  - pip:
    - requests
    - awscli
    - keras-tuner