channels:
  - conda-forge
dependencies:
  - nodejs
  - pip
  - python=3.10
  - pip:
    # https://github.com/yaml/pyyaml/issues/601
    - PyYAML==6.0.1
    - aws-cdk-lib
    - awscli
    - beautifulsoup4
    - black
    - boto3
    - cachetools
    - clize
    - dataclass-wizard
    - docker
    - fiftyone
    - ftfy
    - git-remote-codecommit
    - ipykernel
    - ipython
    - ipywidgets
    - kaggle
    - keras-cv
    - keras-tuner
    - lxml
    - matplotlib
    - mlflow==2.16.1
    - mypy
    - nbconvert
    - nbformat
    - numpy
    - pandas
    - polars
    - pyarrow
    - pytest
    - python-dotenv
    - regex
    - requests
    - s3fs
    - sagemaker
    - scikit-learn
    - seaborn
    - statsmodels
    - tables
    - tensorflow[and-cuda]
    - tqdm
    - transformers