channels:
  - conda-forge
  - pytorch
dependencies:
  - nodejs
  - numpy
  - pandas
  - pip
  - python
  - pytorch
  - tensorflow=2.8.1=cuda*
  - torchvision
  - pip:
    - aws-cdk-lib
    - awscli
    - beautifulsoup4
    - black
    - boto3
    - cachetools
    - clize
    - dataclass-wizard
    - docker
    - fiftyone
    - ftfy
    - git-remote-codecommit
    - ipykernel
    - ipython
    - ipywidgets
    - kaggle
    - keras-tuner
    - line_profiler
    - lxml
    - matplotlib
    - mlflow==2.16.1
    - mypy
    - nbconvert
    - nbformat
    - polars
    - protobuf==3.20
    - pyarrow
    - pytest
    - python-dotenv
    # https://github.com/yaml/pyyaml/issues/601
    - PyYAML==6.0.1
    - regex
    - requests
    - sagemaker
    - s3fs
    - scikit-learn
    - seaborn
    - statsmodels
    - tables
    - tensorflow-hub==0.15.0
    - tensorflow_addons
    - tqdm
    - transformers
