dependencies:
  - nodejs
  - numpy
  - pandas
  - pip
  - python
  - tensorflow=2.8.1=cuda*
  - pip:
    - aws-cdk-lib
    - awscli
    - black
    - boto3
    - cachetools
    - clize
    - dataclass-wizard
    - docker
    - fiftyone
    - ftfy
    - git+https://github.com/divamgupta/stable-diffusion-tensorflow.git@2873079b49eda63f41267c69b825e03cbcb2c308
    - ipykernel
    - ipython
    - ipywidgets
    - kaggle
    - keras-tuner
    - line_profiler
    - matplotlib
    - mypy
    - protobuf
    - pyarrow
    - python-dotenv
    - regex
    - requests
    - s3fs
    - scikit-learn
    - seaborn
    - statsmodels
    - tensorflow-hub
    - tensorflow_addons
    - tqdm
    - transformers